[workspace]
resolver = "2"
members = ["crates/*"]
default-members = ["crates/ski"]

[workspace.dependencies]
ski-draw = { path = "./crates/ski-draw" }
winit = "0.30.5"
wgpu = "23.0.0"
async-task = "4.7.1"
async-std = "1.13.0"
env_logger = "0.11.5"
log = "0.4.22"
chrono = "0.4.38"
