[package]
name = "ski"
version = "0.1.0"
edition = "2021"

[dependencies]
winit.workspace = true
ski-draw.workspace = true
async-std.workspace = true
env_logger.workspace = true
log.workspace = true
chrono.workspace = true
